# Pull tomcat latest image from dockerhub 
From tomcat:latest

# Maintainer
MAINTAINER "Shufai" 

RUN cp -R /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps
# copy war file on to container 
COPY ./*.war /usr/local/tomcat/webapps